Repository BullWooStar/team5-mini-project, pull requests merged in 2022-09, with the labels that each got.

#21 Button 컴포넌트 구현
  src/components/UI/Button/index.jsx
  src/components/UI/Button/style.js
  src/components/UI/Card/index.jsx
  src/pages/product/Cart.jsx
  src/store/index.js
  src/store/slices/cart-slice.js
Labels: 🎨 HTML & CSS

#16 Curation Page 제작 및 curation-slice 구현
  src/App.js
  src/pages/product/CurationPage.jsx
  src/store/index.js
  src/store/slices/curation-product-slice.js
Labels: 🎨 HTML & CSS, ✨ Feature, 🙏 feedback

#22 Promotion Page 제작 및 promotion-slice 구현
  src/pages/product/PromotionPage.jsx
  src/store/index.js
  src/store/slices/promotion-product-slice.js
Labels: 🎨 HTML & CSS, ✨ Feature

#29 Cart 컴포넌트 수정 & Modal 컴포넌트 구현
  src/components/UI/Modal/index.jsx
  src/components/UI/Modal/style.js
  src/pages/product/Cart.jsx
  src/store/slices/cart-slice.js
Labels: 🎨 HTML & CSS, ✨ Feature

#30 All product page refactoring
  package-lock.json
  src/components/Filter.jsx
  src/components/SearchInput.jsx
  src/pages/product/AllProductPage.jsx
  src/store/index.js
  src/store/slices/all-product-slice.js
  src/store/slices/shown-product-slice.js
  yarn.lock
Labels: 🔨 Refactor

#31 공통 Button 컴포넌트 수정 구현
  src/components/UI/Button/index.jsx
Labels: 🎨 HTML & CSS

#23 Header 컴포넌트 구현
  src/components/Header/index.jsx
  src/components/Header/style.js
Labels: 🎨 HTML & CSS, ✨ Feature

#25 NavBar 컴포넌트 구현
  src/components/Header/index.jsx
  src/components/Header/style.js
  src/components/NavBar/index.jsx
  src/components/NavBar/style.js
Labels: 🙏 feedback

#41 Header 컴포넌트 Cart구현
  src/App.js
  src/components/Header/index.jsx
  src/components/Header/style.js
Labels: 🎨 HTML & CSS, ✨ Feature

#47 전체영역 가운데 정렬 레이아웃 추가
  src/App.js
  src/components/UI/StyleLayout/index.jsx
  src/components/UI/StyleLayout/style.js
Labels: 🎨 HTML & CSS

#39 notfound 컴포넌트 제작
  src/pages/NotFound.jsx
Labels: 🎨 HTML & CSS, ✨ Feature

#51 Header 컴포넌트 리팩토링
  src/components/Header/index.jsx
  src/components/Header/style.js
  src/index.css
Labels: 🎨 HTML & CSS, 🔨 Refactor

#52 Card 컴포넌트 리팩토링
  src/components/UI/Card/index.jsx
  src/utils/constants.js
Labels: 🔨 Refactor

#54 HomePage 컴포넌트 스타일 수정
  public/favicon.ico
  public/images/home_logo.png
  public/index.html
  src/components/UI/Button/index.jsx
  src/pages/HomePage.jsx
Labels: 🎨 HTML & CSS

#61 Promotion page, promotion-slice API 연결
  src/components/UI/StyleLayout/index.jsx
  src/pages/product/PromotionPage.jsx
  src/store/slices/promotion-product-slice.js
Labels: 🎨 HTML & CSS, 📬 API, 🔨 Refactor

#50 NavBar style 수정
  package.json
  src/App.js
  src/components/NavBar/index.jsx
  src/components/NavBar/style.js
  yarn.lock
Labels: 🙏 feedback

#67 Curation page 스타일 수정 및 curation-slice API 연결
  src/components/DropDown.js
  src/components/UI/StyleLayout/style.js
  src/pages/auth/LoginPage.jsx
  src/pages/auth/SignUpPage.jsx
  src/pages/auth/style.js
  src/pages/product/CurationPage.jsx
  src/store/slices/curation-product-slice.js
Labels: 🎨 HTML & CSS, 📬 API

#70 design: 로그인, 회원가입 페이지 스타일 수정 - #68
  src/components/UI/StyleLayout/style.js
  src/pages/auth/LoginPage.jsx
  src/pages/auth/SignUpPage.jsx
  src/pages/auth/style.js
Labels: 🎨 HTML & CSS
